// This file was auto-generated by ML.NET Model Builder. 

using System;
using FloodManagementML.Model;

namespace FloodManagementML.ConsoleApp
{
    class Program
    {
        static void Main(string[] args)
        {
            // Create single instance of sample data from first line of dataset for model input
            ModelInput sampleData = new ModelInput()
            {
                Distance = 534F,
                Temperature = 23.6F,
                Humidity = 77.4F,
                Time = 5F,
            };

            // Make a single prediction on the sample data and print results
            var predictionResult = ConsumeModel.Predict(sampleData);

            Console.WriteLine("Using model to make single prediction -- Comparing actual Wind_Speed with predicted Wind_Speed from sample data...\n\n");
            Console.WriteLine($"Distance: {sampleData.Distance}");
            Console.WriteLine($"Temperature: {sampleData.Temperature}");
            Console.WriteLine($"Humidity: {sampleData.Humidity}");
            Console.WriteLine($"Time: {sampleData.Time}");
            Console.WriteLine($"\n\nPredicted Wind_Speed: {predictionResult.Score}\n\n");
            Console.WriteLine("=============== End of process, hit any key to finish ===============");
            Console.ReadKey();
        }
    }
}
